version: '3.8'
#volumes:
#  portainer_data:

services:   
  portainer_agent:
    image: portainer/agent
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer_ce:
    image: portainer/portainer-ce
    command: -H tcp://portainer_agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - c:/Users/Matthijs-server/Documents/Repos/home-server/portainer_ce/data:/data
   
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - c:/Users/Matthijs-server/Documents/Repos/home-server/home-assistant/config:/config
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8123:8123
    restart: unless-stopped
    privileged: true
       
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=Europe/Amsterdam
      - PLEX_CLAIM=claim--LYYTVwKJEytssSpBuFY
    volumes:
      - c:/Users/Matthijs-server/Documents/Repos/home-server/plex/config:/config
      - d:/Matthijs/Movies:/movies
      - d:/Matthijs/Series:/series
      - d:/Matthijs/Pictures:/pictures
      - d:/Matthijs/Videos:/videos
    ports:
    # For Plex remote to work make sure that port forwarding is enabled on the router
      - 32400:32400
      - 1900:1900
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32469:32469
      
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - c:/Users/Matthijs-server/Documents/Repos/home-server/resilio-sync/config:/config
      - d:/Ben:/sync/ben
      - d:/Mark:/sync/mark
      - d:/Matthijs:/sync/matthijs
      - d:/Meike:/sync/meike
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
  
  deluge:
    container_name: deluge
    restart: unless-stopped
    ports:
     - 8112:8112
     - 6881:6881
     - 6881:6881/udp
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Amsterdam
     - UMASK_SET=000 
     - DELUGE_LOGLEVEL=error 
    volumes:
     - c:/Users/Matthijs-server/Documents/Repos/home-server/deluge/config/:/config
     - d:/Matthijs/Deluge/:/downloads
    image: linuxserver/deluge